# Generated by Django 4.2.6 on 2023-12-13 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=40, null=True, unique=True)),
                ('name', models.CharField(max_length=80, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('locale', models.CharField(max_length=10, null=True)),
                ('url', models.URLField(null=True)),
                ('sales', models.JSONField(null=True)),
                ('dates', models.JSONField(null=True)),
                ('please_note', models.TextField(null=True)),
                ('price_range', models.JSONField(null=True)),
                ('promoter', models.JSONField(null=True)),
                ('images', models.JSONField(null=True)),
                ('info', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('promoters', models.JSONField(null=True)),
                ('outlets', models.JSONField(null=True)),
                ('products', models.JSONField(null=True)),
                ('seatmap', models.JSONField(null=True)),
                ('accessibility', models.JSONField(null=True)),
                ('ticket_limit', models.JSONField(null=True)),
                ('external_links', models.JSONField(null=True)),
                ('aliases', models.JSONField(null=True)),
                ('localized_aliases', models.JSONField(null=True)),
                ('venue_id', models.CharField(max_length=40, null=True)),
                ('venue_name', models.CharField(max_length=80, null=True)),
                ('venue_type', models.CharField(max_length=50, null=True)),
                ('venue_locale', models.CharField(max_length=10, null=True)),
                ('venue_url', models.URLField(null=True)),
                ('venue_location', models.JSONField(null=True)),
                ('venue_markets', models.JSONField(null=True)),
                ('venue_timezone', models.CharField(max_length=100, null=True)),
                ('venue_address', models.JSONField(null=True)),
                ('venue_city', models.JSONField(null=True)),
                ('venue_state', models.JSONField(null=True)),
                ('venue_country', models.JSONField(null=True)),
                ('venue_postal_code', models.CharField(max_length=10, null=True)),
                ('venue_dmas', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=80, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('locale', models.CharField(max_length=10, null=True)),
                ('location', models.JSONField()),
                ('timezone', models.CharField(max_length=100, null=True)),
                ('address', models.JSONField()),
                ('city', models.JSONField()),
                ('state', models.JSONField()),
                ('country', models.JSONField()),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('dmas', models.JSONField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='ticket_master.event', to_field='event_id')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_master.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(default='', max_length=100)),
                ('segment_name', models.CharField(default='', max_length=100)),
                ('family', models.BooleanField(null=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='ticket_master.event', to_field='event_id')),
            ],
        ),
    ]
