# Generated by Django 4.2.6 on 2023-12-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='ticket_master.venue', to_field='event_id'),
        ),
    ]
