# Generated by Django 4.2.6 on 2023-12-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_master', '0002_alter_classification_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='venue',
        ),
        migrations.AddField(
            model_name='event',
            name='genre_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
