# Generated by Django 4.2.6 on 2024-01-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_master', '0005_event_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
