# Generated by Django 4.2.6 on 2024-01-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_master', '0006_alter_event_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
