# Generated by Django 4.2.6 on 2024-02-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_master', '0007_alter_event_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_id',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_locale',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_postal_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_timezone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='locale',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='postal_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='timezone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_id',
            field=models.CharField(max_length=100),
        ),
    ]
